export interface ColorScheme {
  textPrimary: string;
  textSecondary: string;
  textAccent: string;
  textNeutral: string;

  bgPrimary: string;
  bgSecondary: string;
  bgAccent: string;
  bgNeutral: string;

  borderPrimary: string;
  borderSecondary: string;
  borderAccent: string;
  borderNeutral: string;

  placeholderPrimary: string;
  placeholderSecondary: string;
  placeholderAccent: string;
  placeholderNeutral: string;

  // Add more prefixes and colors as needed
}

export enum Theme {
  Dark = 'dark',
  Light = 'light',
  Forest = 'forest',
  Ocean = 'ocean',
  Sunrise = 'sunrise',
  Twilight = 'twilight',
  Coral = 'coral',
  Mint = 'mint',
  Sunset = 'sunset',
  Midnight = 'midnight',
  Azure = 'azure',
  Rose = 'rose',
  Orchid = 'orchid',
  Amber = 'amber',
  Serene = 'serene',
  Dusk = 'dusk',
  Ruby = 'ruby',
  Citrus = 'citrus',
  Emerald = 'emerald',
  Ivory = 'ivory',
}

export const ThemeColorSchemes: { [key in Theme]: ColorScheme } = {
  [Theme.Dark]: {
    textPrimary: 'text-white',
    textSecondary: 'text-gray-800',
    textAccent: 'text-teal-500',
    textNeutral: 'text-gray-500',
    bgPrimary: 'bg-blue-gray-200',
    bgSecondary: 'bg-gray-500',
    bgAccent: 'bg-teal-500',
    bgNeutral: 'bg-gray-900',
    borderPrimary: 'border-blue-gray-800',
    borderSecondary: 'border-gray-500',
    borderAccent: 'border-teal-500',
    borderNeutral: 'border-gray-900',
    placeholderPrimary: 'placeholder-blue-gray-800',
    placeholderSecondary: 'placeholder-gray-500',
    placeholderAccent: 'placeholder-teal-500',
    placeholderNeutral: 'placeholder-gray-900',
    // Add more color values
  },
  [Theme.Light]: {
    textPrimary: 'text-gray-800',
    textSecondary: 'text-gray-500',
    textAccent: 'text-pink-500',
    textNeutral: 'text-gray-700',
    bgPrimary: 'bg-gray-100',
    bgSecondary: 'bg-gray-300',
    bgAccent: 'bg-pink-500',
    bgNeutral: 'bg-gray-50',
    borderPrimary: 'border-gray-100',
    borderSecondary: 'border-gray-300',
    borderAccent: 'border-pink-500',
    borderNeutral: 'border-gray-50',
    placeholderPrimary: 'placeholder-gray-100',
    placeholderSecondary: 'placeholder-gray-300',
    placeholderAccent: 'placeholder-pink-500',
    placeholderNeutral: 'placeholder-gray-50',
    // Add more color values
  },
  [Theme.Forest]: {
    textPrimary: 'text-gray-800',
    textSecondary: 'text-gray-500',
    textAccent: 'text-lime-400',
    textNeutral: 'text-gray-700',
    bgPrimary: 'bg-green-600',
    bgSecondary: 'bg-green-300',
    bgAccent: 'bg-lime-400',
    bgNeutral: 'bg-green-200',
    borderPrimary: 'border-green-600',
    borderSecondary: 'border-green-300',
    borderAccent: 'border-lime-400',
    borderNeutral: 'border-green-200',
    placeholderPrimary: 'placeholder-green-600',
    placeholderSecondary: 'placeholder-green-300',
    placeholderAccent: 'placeholder-lime-400',
    placeholderNeutral: 'placeholder-green-200',
    // Add more color values
  },
  [Theme.Ocean]: {
    textPrimary: 'text-gray-800',
    textSecondary: 'text-gray-500',
    textAccent: 'text-cyan-400',
    textNeutral: 'text-gray-700',
    bgPrimary: 'bg-teal-600',
    bgSecondary: 'bg-teal-300',
    bgAccent: 'bg-cyan-400',
    bgNeutral: 'bg-teal-200',
    borderPrimary: 'border-teal-600',
    borderSecondary: 'border-teal-300',
    borderAccent: 'border-cyan-400',
    borderNeutral: 'border-teal-200',
    placeholderPrimary: 'placeholder-teal-600',
    placeholderSecondary: 'placeholder-teal-300',
    placeholderAccent: 'placeholder-cyan-400',
    placeholderNeutral: 'placeholder-teal-200',
    // Add more color values
  },
  [Theme.Sunrise]: {
    textPrimary: 'text-gray-800',
    textSecondary: 'text-gray-500',
    textAccent: 'text-yellow-400',
    textNeutral: 'text-gray-700',
    bgPrimary: 'bg-orange-600',
    bgSecondary: 'bg-amber-300',
    bgAccent: 'bg-yellow-400',
    bgNeutral: 'bg-orange-200',
    borderPrimary: 'border-orange-600',
    borderSecondary: 'border-amber-300',
    borderAccent: 'border-yellow-400',
    borderNeutral: 'border-orange-200',
    placeholderPrimary: 'placeholder-orange-600',
    placeholderSecondary: 'placeholder-amber-300',
    placeholderAccent: 'placeholder-yellow-400',
    placeholderNeutral: 'placeholder-orange-200',
    // Add more color values
  },
  [Theme.Twilight]: {
    textPrimary: 'text-gray-800',
    textSecondary: 'text-gray-500',
    textAccent: 'text-indigo-400',
    textNeutral: 'text-gray-700',
    bgPrimary: 'bg-purple-600',
    bgSecondary: 'bg-violet-300',
    bgAccent: 'bg-indigo-400',
    bgNeutral: 'bg-purple-200',
    borderPrimary: 'border-purple-600',
    borderSecondary: 'border-violet-300',
    borderAccent: 'border-indigo-400',
    borderNeutral: 'border-purple-200',
    placeholderPrimary: 'placeholder-purple-600',
    placeholderSecondary: 'placeholder-violet-300',
    placeholderAccent: 'placeholder-indigo-400',
    placeholderNeutral: 'placeholder-purple-200',
    // Add more color values
  },
  [Theme.Coral]: {
    textPrimary: 'text-gray-800',
    textSecondary: 'text-gray-500',
    textAccent: 'text-orange-400',
    textNeutral: 'text-gray-700',
    bgPrimary: 'bg-red-600',
    bgSecondary: 'bg-pink-300',
    bgAccent: 'bg-orange-400',
    bgNeutral: 'bg-red-200',
    borderPrimary: 'border-red-600',
    borderSecondary: 'border-pink-300',
    borderAccent: 'border-orange-400',
    borderNeutral: 'border-red-200',
    placeholderPrimary: 'placeholder-red-600',
    placeholderSecondary: 'placeholder-pink-300',
    placeholderAccent: 'placeholder-orange-400',
    placeholderNeutral: 'placeholder-red-200',
    // Add more color values
  },
  [Theme.Mint]: {
    textPrimary: 'text-gray-800',
    textSecondary: 'text-gray-500',
    textAccent: 'text-lime-400',
    textNeutral: 'text-gray-700',
    bgPrimary: 'bg-emerald-600',
    bgSecondary: 'bg-green-300',
    bgAccent: 'bg-lime-400',
    bgNeutral: 'bg-emerald-200',
    borderPrimary: 'border-emerald-600',
    borderSecondary: 'border-green-300',
    borderAccent: 'border-lime-400',
    borderNeutral: 'border-emerald-200',
    placeholderPrimary: 'placeholder-emerald-600',
    placeholderSecondary: 'placeholder-green-300',
    placeholderAccent: 'placeholder-lime-400',
    placeholderNeutral: 'placeholder-emerald-200',
    // Add more color values
  },
  [Theme.Sunset]: {
    textPrimary: 'text-gray-800',
    textSecondary: 'text-gray-500',
    textAccent: 'text-red-400',
    textNeutral: 'text-gray-700',
    bgPrimary: 'bg-yellow-600',
    bgSecondary: 'bg-amber-300',
    bgAccent: 'bg-red-400',
    bgNeutral: 'bg-yellow-200',
    borderPrimary: 'border-yellow-600',
    borderSecondary: 'border-amber-300',
    borderAccent: 'border-red-400',
    borderNeutral: 'border-yellow-200',
    placeholderPrimary: 'placeholder-yellow-600',
    placeholderSecondary: 'placeholder-amber-300',
    placeholderAccent: 'placeholder-red-400',
    placeholderNeutral: 'placeholder-yellow-200',
    // Add more color values
  },
  [Theme.Midnight]: {
    textPrimary: 'text-gray-100',
    textSecondary: 'text-gray-300',
    textAccent: 'text-cyan-400',
    textNeutral: 'text-gray-200',
    bgPrimary: 'bg-blue-800',
    bgSecondary: 'bg-indigo-600',
    bgAccent: 'bg-cyan-400',
    bgNeutral: 'bg-blue-900',
    borderPrimary: 'border-blue-800',
    borderSecondary: 'border-indigo-600',
    borderAccent: 'border-cyan-400',
    borderNeutral: 'border-blue-900',
    placeholderPrimary: 'placeholder-blue-800',
    placeholderSecondary: 'placeholder-indigo-600',
    placeholderAccent: 'placeholder-cyan-400',
    placeholderNeutral: 'placeholder-blue-900',
    // Add more color values
  },
  [Theme.Azure]: {
    textPrimary: 'text-gray-800',
    textSecondary: 'text-gray-500',
    textAccent: 'text-blue-400',
    textNeutral: 'text-gray-700',
    bgPrimary: 'bg-blue-500',
    bgSecondary: 'bg-light-blue-300',
    bgAccent: 'bg-blue-400',
    bgNeutral: 'bg-blue-200',
    borderPrimary: 'border-blue-500',
    borderSecondary: 'border-light-blue-300',
    borderAccent: 'border-blue-400',
    borderNeutral: 'border-blue-200',
    placeholderPrimary: 'placeholder-blue-500',
    placeholderSecondary: 'placeholder-light-blue-300',
    placeholderAccent: 'placeholder-blue-400',
    placeholderNeutral: 'placeholder-blue-200',
    // Add more color values
  },
  [Theme.Rose]: {
    textPrimary: 'text-gray-800',
    textSecondary: 'text-gray-500',
    textAccent: 'text-rose-400',
    textNeutral: 'text-gray-700',
    bgPrimary: 'bg-red-500',
    bgSecondary: 'bg-rose-300',
    bgAccent: 'bg-rose-400',
    bgNeutral: 'bg-rose-200',
    borderPrimary: 'border-red-500',
    borderSecondary: 'border-rose-300',
    borderAccent: 'border-rose-400',
    borderNeutral: 'border-rose-200',
    placeholderPrimary: 'placeholder-red-500',
    placeholderSecondary: 'placeholder-rose-300',
    placeholderAccent: 'placeholder-rose-400',
    placeholderNeutral: 'placeholder-rose-200',
    // Add more color values
  },
  [Theme.Orchid]: {
    textPrimary: 'text-gray-800',
    textSecondary: 'text-gray-500',
    textAccent: 'text-purple-400',
    textNeutral: 'text-gray-700',
    bgPrimary: 'bg-purple-500',
    bgSecondary: 'bg-violet-300',
    bgAccent: 'bg-purple-400',
    bgNeutral: 'bg-purple-200',
    borderPrimary: 'border-purple-500',
    borderSecondary: 'border-violet-300',
    borderAccent: 'border-purple-400',
    borderNeutral: 'border-purple-200',
    placeholderPrimary: 'placeholder-purple-500',
    placeholderSecondary: 'placeholder-violet-300',
    placeholderAccent: 'placeholder-purple-400',
    placeholderNeutral: 'placeholder-purple-200',
    // Add more color values
  },
  [Theme.Amber]: {
    textPrimary: 'text-gray-800',
    textSecondary: 'text-gray-500',
    textAccent: 'text-amber-400',
    textNeutral: 'text-gray-700',
    bgPrimary: 'bg-yellow-500',
    bgSecondary: 'bg-amber-300',
    bgAccent: 'bg-amber-400',
    bgNeutral: 'bg-amber-200',
    borderPrimary: 'border-yellow-500',
    borderSecondary: 'border-amber-300',
    borderAccent: 'border-amber-400',
    borderNeutral: 'border-amber-200',
    placeholderPrimary: 'placeholder-yellow-500',
    placeholderSecondary: 'placeholder-amber-300',
    placeholderAccent: 'placeholder-amber-400',
    placeholderNeutral: 'placeholder-amber-200',
    // Add more color values
  },
  [Theme.Serene]: {
    textPrimary: 'text-gray-800',
    textSecondary: 'text-gray-500',
    textAccent: 'text-blue-500',
    textNeutral: 'text-gray-700',
    bgPrimary: 'bg-white',
    bgSecondary: 'bg-gray-100',
    bgAccent: 'bg-blue-200',
    bgNeutral: 'bg-gray-50',
    borderPrimary: 'border-white',
    borderSecondary: 'border-gray-100',
    borderAccent: 'border-blue-200',
    borderNeutral: 'border-gray-50',
    placeholderPrimary: 'placeholder-white',
    placeholderSecondary: 'placeholder-gray-100',
    placeholderAccent: 'placeholder-blue-200',
    placeholderNeutral: 'placeholder-gray-50',
    // Add more color values
  },
  [Theme.Dusk]: {
    textPrimary: 'text-slate-300',
    textSecondary: 'text-slate-400',
    textAccent: 'text-indigo-500',
    textNeutral: 'text-slate-100',
    bgPrimary: 'bg-gray-900',
    bgSecondary: 'bg-indigo-800',
    bgAccent: 'bg-indigo-700',
    bgNeutral: 'bg-indigo-200',
    borderPrimary: 'border-gray-900',
    borderSecondary: 'border-indigo-800',
    borderAccent: 'border-indigo-700',
    borderNeutral: 'border-indigo-600',
    placeholderPrimary: 'placeholder-gray-900',
    placeholderSecondary: 'placeholder-indigo-800',
    placeholderAccent: 'placeholder-indigo-700',
    placeholderNeutral: 'placeholder-indigo-600',
    // Add more color values
  },
  [Theme.Ruby]: {
    textPrimary: 'text-gray-800',
    textSecondary: 'text-gray-500',
    textAccent: 'text-red-500',
    textNeutral: 'text-gray-700',
    bgPrimary: 'bg-red-800',
    bgSecondary: 'bg-rose-800',
    bgAccent: 'bg-red-700',
    bgNeutral: 'bg-rose-700',
    borderPrimary: 'border-red-800',
    borderSecondary: 'border-rose-800',
    borderAccent: 'border-red-700',
    borderNeutral: 'border-rose-700',
    placeholderPrimary: 'placeholder-red-800',
    placeholderSecondary: 'placeholder-rose-800',
    placeholderAccent: 'placeholder-red-700',
    placeholderNeutral: 'placeholder-rose-700',
    // Add more color values
  },
  [Theme.Citrus]: {
    textPrimary: 'text-gray-800',
    textSecondary: 'text-gray-500',
    textAccent: 'text-yellow-500',
    textNeutral: 'text-gray-700',
    bgPrimary: 'bg-yellow-300',
    bgSecondary: 'bg-amber-300',
    bgAccent: 'bg-yellow-200',
    bgNeutral: 'bg-amber-200',
    borderPrimary: 'border-yellow-300',
    borderSecondary: 'border-amber-300',
    borderAccent: 'border-yellow-200',
    borderNeutral: 'border-amber-200',
    placeholderPrimary: 'placeholder-yellow-300',
    placeholderSecondary: 'placeholder-amber-300',
    placeholderAccent: 'placeholder-yellow-200',
    placeholderNeutral: 'placeholder-amber-200',
    // Add more color values
  },
  [Theme.Emerald]: {
    textPrimary: 'text-gray-800',
    textSecondary: 'text-gray-500',
    textAccent: 'text-emerald-500',
    textNeutral: 'text-gray-700',
    bgPrimary: 'bg-emerald-500',
    bgSecondary: 'bg-green-500',
    bgAccent: 'bg-emerald-400',
    bgNeutral: 'bg-green-400',
    borderPrimary: 'border-emerald-500',
    borderSecondary: 'border-green-500',
    borderAccent: 'border-emerald-400',
    borderNeutral: 'border-green-400',
    placeholderPrimary: 'placeholder-emerald-500',
    placeholderSecondary: 'placeholder-green-500',
    placeholderAccent: 'placeholder-emerald-400',
    placeholderNeutral: 'placeholder-green-400',
    // Add more color values
  },
  [Theme.Ivory]: {
    textPrimary: 'text-gray-800',
    textSecondary: 'text-gray-500',
    textAccent: 'text-white',
    textNeutral: 'text-gray-700',
    bgPrimary: 'bg-gray-200',
    bgSecondary: 'bg-gray-300',
    bgAccent: 'bg-white',
    bgNeutral: 'bg-gray-100',
    borderPrimary: 'border-gray-200',
    borderSecondary: 'border-gray-300',
    borderAccent: 'border-white',
    borderNeutral: 'border-gray-100',
    placeholderPrimary: 'placeholder-gray-200',
    placeholderSecondary: 'placeholder-gray-300',
    placeholderAccent: 'placeholder-white',
    placeholderNeutral: 'placeholder-gray-100',
    // Add more color values
  },
};
